### ISSUE TITLE
Interface of Edit Store needs Enhancement.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#58]
**Steps to replicate**
1. Log in as merchant
2. Navigate to Setting --> Edit Store.

**Actual Result**
> The values of open time and close time were not fitted in its cell.
> The content of the Action panel is not consistent.
     - Open button and Check boxes.
> Title is very confusing. " Edit Store Name store information "

**Expected Result**
>The values of open time and close time should be fitted in its cell and can be viewed clearly by the user.
> The action panel should only contain the button for open and close, not the check boxes.
> Title should be "Edit Store Information"

![screen shot 2015-01-15 at 2 46 02 pm](https://cloud.githubusercontent.com/assets/9795882/5753672/81ca20c6-9cc7-11e4-932b-c420de0fa9d3.png)

![screen shot 2015-01-15 at 2 42 10 pm](https://cloud.githubusercontent.com/assets/9795882/5753595/cc327682-9cc6-11e4-9ca8-15d66ba65913.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
