### ISSUE TITLE
12 Hour Clock System invalid implementation.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#59]
**Steps to replicate**
1. Log in as merchant
2. Navigate to Settings --> Edit Store
3. Unchecked the Action on Store Schedule

**Actual Result**
Invalid time has been saved and updated successfully.

**Expected Result**
Since it includes am and pm in time frame, it means that it implies a 12 hour clock system. below 1 o'clock and above 12 o'clock, value should not be accepted.

![screen shot 2015-01-15 at 5 26 07 pm](https://cloud.githubusercontent.com/assets/9795882/5755110/a0c4a26c-9cdb-11e4-8058-c94a97f6423d.png)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
