### ISSUE TITLE
Incompatibility of action button in mozilla firefox v. 34.0.5

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#60]
**Steps to replicate**
1. Open both firefox and google chrome browser.
2. Navigate to Crowd to Go Login page.
3. Login as Merchant.
4. Navigate to Setting --> Edit Store.

**Actual Result** Edit store UI in google chrome displays different output from the mozilla firefox. The action panel in google chrome display the open and close button while in firefox it display checkboxes for the action of store schedule.

**Expected Result** Different browser should still have the same interface output.

![screen shot 2015-01-15 at 5 29 52 pm](https://cloud.githubusercontent.com/assets/9795882/5755229/25ac1afe-9cdd-11e4-96fc-8ee40bfeef16.png)

![screen shot 2015-01-15 at 5 30 21 pm](https://cloud.githubusercontent.com/assets/9795882/5755321/0ed4bee8-9cde-11e4-8626-c4dd543b599d.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
