### ISSUE TITLE
Buttons in Action Panel of Store Schedule cannot be updated

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#61]
**Steps to replicate**
1. Navigate to Crowd to Go Login page in Mozilla Firefox v. 35.0
2. Login as merchant
3. Navigate to Settings --> Edit Store
4. Unchecked the check boxes in action panel.
5. Click the open button in action panel.
6. Click Update Store Details.

**Actual Result**
> Unchecked check boxes remain checked when the page refreshes after hitting the update store details button.
> Open store schedule doesn't change into close one, after hitting the button in action panel.

**Expected Result**
> Open and close schedule of the store must be changed after the update.

![screen shot 2015-01-16 at 9 20 00 am](https://cloud.githubusercontent.com/assets/9795882/5770141/2950448a-9d61-11e4-84a4-9de364156db4.png)
![screen shot 2015-01-16 at 9 20 37 am](https://cloud.githubusercontent.com/assets/9795882/5770142/295873ee-9d61-11e4-8257-2c96e200e669.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
