### ISSUE TITLE
No Character Limit for Street Address in Merchant: Edit Account

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#62]
**Steps to replicate**
1. Login as Merchant in Crowd to Go.
2. Navigate to Settings --> Edit Account
3. Input long characters in street address field.

**Actual Result** User can input infinite characters in the street address field.

**Expected Result** Street address field should have a maximum character limit.

![screen shot 2015-01-16 at 9 44 26 am](https://cloud.githubusercontent.com/assets/9795882/5770362/4c596c56-9d64-11e4-9cd9-7512939c5141.png)

**Comment by johnarben2468** [comment]
fixed maxlength=  100

**Comment by barbacenasmc** [comment]
Issue fix was already verfied.
