### ISSUE TITLE
Merchant: Edit Account: Input of Numerical Characters in the Name Fields should be not be Validated.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#64]
**Steps to replicate**
1. Login a s Merchant.
2. Navigate to Settings --> Edit Account.
3. Input numerical characters in the name fields.
4. Click submit.

**Actual Result** It displays a validation message indicating that the first name/ last name may only contain letters, numbers, dash, spaces and apostrophe but still doesn't accepts numbers.

**Expected Result** Exception of number acceptance should be remove from the validation message of the name fields.

![screen shot 2015-01-16 at 10 40 33 am](https://cloud.githubusercontent.com/assets/9795882/5770808/3cf1986c-9d6c-11e4-84cf-19d82396405a.png)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
