### ISSUE TITLE
Activation of account validation message is repeated.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#65]
**Steps to replicate**
1. Login as merchant.
2. Navigate to Settings --> Deactivate account. (User will be log out)
3. Login the deactivated account.

**Actual Result** Every login that is made by the user, validation message "Your account has been activated" was always shown.

**Expected Result** "Your account has been activated" validation message should only be displayed ones, at the first login after deactivation.

![screen shot 2015-01-16 at 12 01 18 pm](https://cloud.githubusercontent.com/assets/9795882/5771444/43e44014-9d78-11e4-93f0-674aa0eeb167.png)

![screen shot 2015-01-16 at 12 01 21 pm](https://cloud.githubusercontent.com/assets/9795882/5771445/45870dde-9d78-11e4-943c-6ec39a871a94.png)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.

**Comment by Leirum** [comment]
Deactivation of account for merchant user has been removed. Issue closed.
