### ISSUE TITLE
The UI of Merchant Account's Settings Page weren't Responsive.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#67]
**Steps to replicate**
1. Login as Merchant.
2. Resize the browser into small size.
3. Navigate to Settings --> Edit Account.
4. Navigate to Settings --> Edit Store.

**Actual Result** The UI settings of merchant account for the edit account and edit store weren't responsive.

**Expected Result** Responsive design should be implemented according to the size of the browser.

![screen shot 2015-01-16 at 1 12 33 pm](https://cloud.githubusercontent.com/assets/9795882/5771993/7970d4ac-9d84-11e4-97b5-af5c20be3fdc.png)
![screen shot 2015-01-16 at 11 55 29 am](https://cloud.githubusercontent.com/assets/9795882/5771994/797e299a-9d84-11e4-86b1-99132d900802.png)

**Comment by mgeronimo** [comment]
Edit Store page responsiveness fixed.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.

**Comment by Leirum** [comment]
Issue can still be replicated. Please see issue #82
