### ISSUE TITLE
Fields' Value in Merchant's Customer Details Still Remain after the Successful Submission of Order.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#68]
**Steps to replicate**
1. Login as Merchant.
2. Navigate to Submit an Order page.
3. Fill up all the fields.
4. Click Submit.
5. Navigate to Submit an Order page.

**Actual Result** The email, city, date and time of the last submitted customer details still remain.

**Expected Result** All the fields should have its default or null value.

![screen shot 2015-01-16 at 1 47 57 pm](https://cloud.githubusercontent.com/assets/9795882/5772108/c6718e7a-9d86-11e4-98d7-28a2be234155.png)
![screen shot 2015-01-16 at 1 48 30 pm](https://cloud.githubusercontent.com/assets/9795882/5772107/c670ebfa-9d86-11e4-88f7-8843fefea730.png)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
