### ISSUE TITLE
Successful Registration of Merchant's Order without Pick Up Time Value.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#69]
**Steps to replicate**
1. Login as Merchant.
2. Navigate to Submit an Order page.
3. Fill up all fields except for the pick up time.
4. Click Submit.

**Actual Result** Submission of order was successfully registered without the value of pick up time.

**Expected Result** It should display a validation message indicating that pick up time is required.

![screen shot 2015-01-16 at 2 43 38 pm](https://cloud.githubusercontent.com/assets/9795882/5772508/bab0eeca-9d8e-11e4-970a-c401861dc33b.png)
![screen shot 2015-01-16 at 2 45 04 pm](https://cloud.githubusercontent.com/assets/9795882/5772509/bab35ade-9d8e-11e4-8421-254f9889d414.png)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
