### ISSUE TITLE
Settings in Menu Tab is Missing when Merchant Successfully Submitted an Order.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#70]
**Steps to replicate**
1. Login as merchant.
2. Navigate to submit an order page.
3. Fill up all fields with valid values.
4. Click submit.
5. Observe the Menu tab.

**Actual Result** Menu doesn't displays Settings tab.

**Expected Result** Navigation through different pages should have the same menu item lists.

![screen shot 2015-01-16 at 2 59 16 pm](https://cloud.githubusercontent.com/assets/9795882/5772671/12eea22e-9d91-11e4-8c39-45d0fc67e91f.png)

![screen shot 2015-01-16 at 2 58 32 pm](https://cloud.githubusercontent.com/assets/9795882/5772699/9e8ac042-9d91-11e4-816f-49f33dc71bc3.png)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
