### ISSUE TITLE
Logging out and pressing back button can still access "Edit Crowdie Information".

### ISSUE THREAD

**Issue by willvalentin** [mgeronimo/CTG-Apply#73]
Steps to replicate
1. Login as Admin (haven't tried with other accounts yet, there's a high probability that this can happen on other account types as well.)
2. Go to Crowdie Dashboard.
3. Click logout button.
4. Hold back button and go back couple of pages (see screenshot).

Actual Result:
The "Edit Crowdie Information" can still be accessed even though the account is supposed to be logged out.

Expected Result:
Can't access anything and should be back at the log in page.

![logout1](https://cloud.githubusercontent.com/assets/10610837/5815139/c385072e-a0cd-11e4-9082-9ad3baf124b7.PNG)
![logout2](https://cloud.githubusercontent.com/assets/10610837/5815143/cecda4ba-a0cd-11e4-915f-4ea2638bff2b.PNG)
![logout3](https://cloud.githubusercontent.com/assets/10610837/5815147/d51aead0-a0cd-11e4-96b8-6e2fd86800ef.PNG)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue can still be replicated both on chrome and firefox. Tried to do the same with google docs but returned the login page. Thus, this issue is independent of browser type or settings.

**Comment by johnarben2468** [comment]
Devapp filter.php file not update. Fixed

**Comment by Leirum** [comment]
Issue fix was already verified as of now, February 10, 2015.

**Comment by Leirum** [comment]
Issue fix was already verified.
