### ISSUE TITLE
Crowdie Application: All other dates are disabled except for current date on datepicker for birthday

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/CTG-Apply#78]
Steps to replicate:
1. Navigate to step 1 of crowdie application.
2. Click the birth date field to display the datepicker.

Actual result: All other dates are disabled except for current date
Expected result: Dates from current to the past should be enabled.

![image](https://cloud.githubusercontent.com/assets/7791554/5869081/05b5f226-a2ee-11e4-9e5e-463163dfa860.png)

**Comment by emarino0411** [comment]
fixed

**Comment by emarino0411** [comment]
Fixed on latest push as of Feb 9,2015 1:57PM. Please verifiy.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
