### ISSUE TITLE
Message to tell the success of crowdie activation is not in proper letter case

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/CTG-Apply#79]
Steps to replicate:
1. Login as admin.
2. Click activate icon on an existing crowdie with a "Not Available" status.

Actual result: A message on top was displayed saying "account has successfully activated".
Expected result: A message on top should display saying "Account has successfully activated."

![ctg-activate-crowdie](https://cloud.githubusercontent.com/assets/7791554/5869361/f1ab825a-a2f2-11e4-91e9-7775b4f2405a.png)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
