### ISSUE TITLE
Merchant: Submit an Order: Invalid Value for Pick Up Time has been Successfully Created for an Order.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#80]
**Steps to replicate**
1. Log in as Merchant
2. Navigate to Submit an Order.
3. Fill out all fields.
4. Select a pick up date. 
5. Click Submit.

**Actual Result**
- Pick up time will auto-fill its field containing a value of "Choose your time" once a pick up date has been selected.
- Order has been successfully created.

**Expected Result**
- Order should not be successfully created.
- It should display a validation message for pick up time that it is a required field.
- Only valid time format (12 hour clock system) should be accepted for the pick up time field.

![1 1](https://cloud.githubusercontent.com/assets/9795882/6121886/fb9aa2be-b125-11e4-9136-77fa56a571d5.png)
![1](https://cloud.githubusercontent.com/assets/9795882/6121885/fb998e38-b125-11e4-96dd-9db40c10304a.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
