### ISSUE TITLE
Admin Stores Dashboard: Edit Store Information results in an Error Page Navigation

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#83]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Stores Dashboard.
3. Click the Edit Store Information in the Action Panel.

**Actual Result**
- Navigating to Edit Store Page results in an error page.

**Expected Result**
- The page should navigate to Edit Store and the admin should be able to update the Store Information.

![whoops _there_was_an_error _-_2015-02-10_15 42 58](https://cloud.githubusercontent.com/assets/9795882/6123336/f6dadea4-b13b-11e4-986f-209734101e1c.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
