### ISSUE TITLE
Admin: Viewing Merchants Details: Cursor can be placed in the textfields of Store Schedule

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#85]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Merchant Dashboard.
3. Select a Merchant.
4. View Merchant Details.
5. Proceed to Store Schedule Panel and place the cursor in its field.

**Actual Result**
- Cursor can be placed in the fields of Store Schedule.
- User can input a value in the fields.

**Expected Result**
- Textfields should be disabled and it should only be for viewing an information.

![screen shot 2015-02-11 at 10 40 36 am](https://cloud.githubusercontent.com/assets/9795882/6141015/761f7e60-b1da-11e4-9180-1e69bf23ffec.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
