### ISSUE TITLE
Admin: Inappropriate numbering in the column name of crowdie dashboard.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#88]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Crowdie Dashboard.
3. Observe the column Name of the Dashboard.

**Actual Result**
- Inappropriate numbering in every crowdie listed in the dashboard.

**Expected Result**
- It should only display the name of each crowdies; no numbers or special characters included.

![crowdie](https://cloud.githubusercontent.com/assets/9795882/6141431/3e4a2d0e-b1e0-11e4-9408-53bba26cb7a8.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
