### ISSUE TITLE
Admin: Edit Crowdie Information: Misspelled label for Insurance Number

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/CTG-Apply#89]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Crowdie Dashboard.
3. Select a crowdie.
4. Edit Crowdie Information.
5. Look for insurance number field.

**Actual Result**
- Misspelled label for Insurance Number
- Missing a character "N" for number.

**Expected Result**
- It should be correctly spelled as "Insurance Number".

![insurance number](https://cloud.githubusercontent.com/assets/9795882/6141544/72d4db58-b1e2-11e4-80b4-839e1f9caa4d.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
